# Kafka connection details
mp.messaging.connector.liberty-kafka.bootstrap.servers=kafka:9092

# Incoming helloWorld stream
mp.messaging.incoming.helloWorld.connector=liberty-kafka
mp.messaging.incoming.helloWorld.topic=hello.world
mp.messaging.incoming.helloWorld.group.id=consumer-group-a
mp.messaging.incoming.helloWorld.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.helloWorld.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer