# Kafka connection details
# tag::kafkaConfig[]
mp.messaging.connector.liberty-kafka.bootstrap.servers=kafka:9092
# end::kafkaConfig[]

# systemLoad stream
# tag::systemLoad[]
# tag::kafka1[]
mp.messaging.outgoing.helloWorld.connector=liberty-kafka
# end::kafka1[]
# tag::topic1[]
mp.messaging.outgoing.helloWorld.topic=hello.world
# end::topic1[]
# tag::serializer1[]
mp.messaging.outgoing.helloWorld.key.serializer=org.apache.kafka.common.serialization.StringSerializer
# end::serializer1[]
# tag::serializerVal1[]
mp.messaging.outgoing.helloWorld.value.serializer=org.apache.kafka.common.serialization.StringSerializer
# end::serializerVal1[]
# end::systemLoad[]